server {
    listen 8080;
    default_type application/json;
    root /usr/share/nginx/html;

    location = /orders {
        try_files /orders-index.json =404;
    }
    location = /payments {
        try_files /payments-index.json =404;
    }

    location / {
        try_files $uri.json $uri =404;
    }

    error_page 404 = @not_found;
    location @not_found {
        default_type application/json;
        return 404 '{"error":"not found"}';
    }
}
